"""add skills and mcp_servers tables

Revision ID: 0ec5128a2206
Revises: b7c8d9e0f1a2
Create Date: 2026-09-10 18:13:17.696695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec5128a2206'
down_revision: Union[str, Sequence[str], None] = 'b7c8d9e0f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dir_name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index('uq_skills_dir_name', ['dir_name'], unique=True)

    op.create_table('mcp_servers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), server_default=sa.text("('')"), nullable=False),
    sa.Column('server_type', sa.String(length=10), nullable=False),
    sa.Column('command', sa.String(length=500), nullable=True),
    sa.Column('command_args', sa.JSON(), nullable=True),
    sa.Column('env_secret_ref', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('headers_secret_ref', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('last_test_status', sa.String(length=20), nullable=True),
    sa.Column('last_test_message', sa.String(length=2000), nullable=True),
    sa.Column('last_test_tool_count', sa.Integer(), nullable=True),
    sa.Column('last_test_at', sa.DateTime(), nullable=True),
    sa.Column('tools_json', sa.String(length=100000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['env_secret_ref'], ['secrets_vault.id'], ),
    sa.ForeignKeyConstraint(['headers_secret_ref'], ['secrets_vault.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_servers', schema=None) as batch_op:
        batch_op.create_index('ix_mcp_servers_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('uq_mcp_servers_name', ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcp_servers', schema=None) as batch_op:
        batch_op.drop_index('uq_mcp_servers_name')
        batch_op.drop_index('ix_mcp_servers_updated_at')

    op.drop_table('mcp_servers')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index('uq_skills_dir_name')

    op.drop_table('skills')
    # ### end Alembic commands ###
