"""add workspace columns to conversations and runs

Revision ID: 5ece99f8a6b7
Revises: e1f2a3b4c5d6
Create Date: 2026-09-18 14:18:16.939857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ece99f8a6b7'
down_revision: Union[str, Sequence[str], None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('workspace_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('workspace_selected_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_column('workspace_path')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('workspace_selected_at')
        batch_op.drop_column('workspace_source')
        batch_op.drop_column('workspace_path')

    # ### end Alembic commands ###
