"""add runs tables and agent compact fields

Revision ID: 5f009f4ad657
Revises: 207b5aa052ad
Create Date: 2026-09-15 17:53:13.980390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f009f4ad657'
down_revision: Union[str, Sequence[str], None] = '207b5aa052ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_compactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('boundary_seq', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_compactions', schema=None) as batch_op:
        batch_op.create_index('uq_compactions_conversation', ['conversation_id'], unique=True)

    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('reply_message_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_identifier', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('end_reason', sa.String(length=500), server_default=sa.text("('')"), nullable=False),
    sa.Column('error_category', sa.String(length=30), nullable=True),
    sa.Column('error_summary', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('total_duration_ms', sa.Integer(), nullable=True),
    sa.Column('model_call_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tool_call_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('first_output_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index('ix_runs_conversation_id', ['conversation_id'], unique=False)
        batch_op.create_index('ix_runs_started_at', ['started_at'], unique=False)
        batch_op.create_index('ix_runs_status', ['status'], unique=False)
        batch_op.create_index('uq_runs_run_id', ['run_id'], unique=True)

    op.create_table('run_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('call_id', sa.String(length=40), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.create_index('ix_run_events_call_id', ['call_id'], unique=False)
        batch_op.create_index('uq_run_events_run_seq', ['run_id', 'seq'], unique=True)

    op.create_table('run_payloads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('call_id', sa.String(length=40), nullable=False),
    sa.Column('payload_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_payloads', schema=None) as batch_op:
        batch_op.create_index('uq_run_payloads_call_type', ['run_id', 'call_id', 'payload_type'], unique=True)

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_compact', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('compact_trigger_ratio', sa.Numeric(precision=3, scale=2), server_default=sa.text('(0.80)'), nullable=False))
        batch_op.add_column(sa.Column('compact_keep_recent_rounds', sa.Integer(), server_default=sa.text('5'), nullable=False))
        batch_op.add_column(sa.Column('compact_summary_target_tokens', sa.Integer(), server_default=sa.text('(1000)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('compact_summary_target_tokens')
        batch_op.drop_column('compact_keep_recent_rounds')
        batch_op.drop_column('compact_trigger_ratio')
        batch_op.drop_column('auto_compact')

    with op.batch_alter_table('run_payloads', schema=None) as batch_op:
        batch_op.drop_index('uq_run_payloads_call_type')

    op.drop_table('run_payloads')
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.drop_index('uq_run_events_run_seq')
        batch_op.drop_index('ix_run_events_call_id')

    op.drop_table('run_events')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index('uq_runs_run_id')
        batch_op.drop_index('ix_runs_status')
        batch_op.drop_index('ix_runs_started_at')
        batch_op.drop_index('ix_runs_conversation_id')

    op.drop_table('runs')
    with op.batch_alter_table('conversation_compactions', schema=None) as batch_op:
        batch_op.drop_index('uq_compactions_conversation')

    op.drop_table('conversation_compactions')
    # ### end Alembic commands ###
